name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CSV_URL: "Workflow-CI/MLProject/PRSA_Data_Aotizhongxin_preprocessing.csv"  
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out the code from repository
      - uses: actions/checkout@v3

      # Set up Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check environment variable
      - name: Check Env
        run: echo "CSV_URL=$CSV_URL"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install -r MLProject/requirements.txt  

      # Run MLflow Project locally
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local

      # Get the latest MLflow run ID
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV  # Store run_id as GitHub environment variable
          echo "Latest RUN_ID: $RUN_ID"

      # Build Docker image from MLflow model
      - name: Build Docker model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"  # Build the docker image from model

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Use secret for Docker Hub username
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Use secret for Docker Hub token

      # Tag Docker image with 'latest' tag
      - name: Tag Docker image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest  # Tag Docker image with username and 'latest'

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest  # Push the tagged image to Docker Hub
