name: Model Training and Logging

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    # Checkout code dari repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python 3.12.7
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'

    # Install dependencies dari requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MLProject/Requirements.txt 

    # Install MLflow jika belum terpasang
    - name: Install MLflow
      run: |
        pip install mlflow

    # Jalankan model training dari file modelling.py
    - name: Run the model training
      run: |
        python MLProject/Modelling.py

    # Log ke MLflow (jika kamu ingin menjalankan UI MLflow, pastikan sudah siap sebelumnya)
    - name: Log to MLflow
      run: |
        mlflow ui &  
        sleep 10  
