name: MLflow Training to Dagshub

on:
  push:
    branches: [ main ]  # Berjalan otomatis tiap lo push ke main

jobs:
  train-and-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn joblib

      - name: Run Training and Log to MLflow
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Menjalankan script modelling.py dengan parameter yang sesuai
          python modelling.py \
            --input_file "PRSA_Data_Aotizhongxin_preprocessing.csv" \
            --n_estimators 100 \
            --mlflow_tracking_uri "https://dagshub.com/m.ilham2408/my-first-repo.mlflow" \
            --experiment_name "Tugas Akhir MSML"
